# Generated by Django 5.2.8 on 2025-11-12 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('politicians', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='party',
            name='short_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
