# Generated by Django 5.2.8 on 2025-11-12 09:23

from django.db import migrations, models

import politicians.models


class Migration(migrations.Migration):

    dependencies = [
        ("politicians", "0002_alter_party_short_name"),
    ]

    operations = [
        migrations.RenameField(
            model_name="politician",
            old_name="previous_data_history",
            new_name="previous_party_history",
        ),
        migrations.AlterField(
            model_name="politician",
            name="photo",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="media/politicians/",
                validators=[politicians.models.validate_image],
            ),
        ),
    ]
