# Generated by Django 5.2.8 on 2025-11-13 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("politicians", "0004_rating"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rating",
            name="comment",
            field=models.TextField(blank=True, null=True),
        ),
    ]
