# Generated by Django 5.2.8 on 2025-11-15 05:13

import django.db.models.deletion
from django.db import migrations, models

import politicians.models


class Migration(migrations.Migration):

    dependencies = [
        ("politicians", "0005_alter_rating_comment"),
    ]

    operations = [
        migrations.AddField(
            model_name="party",
            name="flag",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="media/party/banners/",
                validators=[politicians.models.validate_image],
            ),
        ),
        migrations.AddField(
            model_name="party",
            name="slug",
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
        migrations.AddField(
            model_name="politician",
            name="location",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="politician",
            name="slug",
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
        migrations.AddField(
            model_name="politician",
            name="views",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="politician",
            name="photo",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="media/politicians/banners/",
                validators=[politicians.models.validate_image],
            ),
        ),
        migrations.CreateModel(
            name="Initiatives",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "politician",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="initiatives",
                        to="politicians.politician",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Promises",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=50,
                    ),
                ),
                (
                    "politician",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="promises",
                        to="politicians.politician",
                    ),
                ),
            ],
        ),
    ]
