# Generated by Django 5.2.8 on 2025-11-15 05:22

import django_extensions.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("politicians", "0006_party_flag_party_slug_politician_location_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="party",
            name="slug",
            field=django_extensions.db.fields.AutoSlugField(
                blank=True,
                editable=False,
                max_length=255,
                populate_from="name",
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="politician",
            name="slug",
            field=django_extensions.db.fields.AutoSlugField(
                blank=True,
                editable=False,
                max_length=255,
                populate_from="name",
                unique=True,
            ),
        ),
    ]
