# Generated by Django 5.2.8 on 2025-11-15 05:37

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import politicians.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('politicians', '0007_alter_party_slug_alter_politician_slug'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='initiatives',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Initiatives'},
        ),
        migrations.AlterModelOptions(
            name='party',
            options={'ordering': ['name'], 'verbose_name_plural': 'Parties'},
        ),
        migrations.AlterModelOptions(
            name='politician',
            options={'ordering': ['-views']},
        ),
        migrations.AlterModelOptions(
            name='promises',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Promises'},
        ),
        migrations.AddField(
            model_name='initiatives',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='initiatives',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='party',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='party',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='politician',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='politician',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Whether the politician is currently active'),
        ),
        migrations.AddField(
            model_name='politician',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='promises',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='promises',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='party',
            name='flag',
            field=models.ImageField(blank=True, help_text='Party flag or logo (max 5MB)', null=True, upload_to='party/banners/', validators=[politicians.models.validate_image]),
        ),
        migrations.AlterField(
            model_name='politician',
            name='age',
            field=models.PositiveIntegerField(help_text='Must be at least 18 years old', validators=[django.core.validators.MinValueValidator(18), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='politician',
            name='biography',
            field=models.TextField(help_text='Detailed biography'),
        ),
        migrations.AlterField(
            model_name='politician',
            name='criminal_record',
            field=models.TextField(blank=True, help_text='Any criminal history or legal issues'),
        ),
        migrations.AlterField(
            model_name='politician',
            name='criticism',
            field=models.TextField(blank=True, help_text='Notable criticisms or controversies'),
        ),
        migrations.AlterField(
            model_name='politician',
            name='education',
            field=models.TextField(help_text='Educational background'),
        ),
        migrations.AlterField(
            model_name='politician',
            name='location',
            field=models.CharField(blank=True, help_text='Current location or constituency', max_length=255),
        ),
        migrations.AlterField(
            model_name='politician',
            name='party',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='politicians', to='politicians.party'),
        ),
        migrations.AlterField(
            model_name='politician',
            name='party_position',
            field=models.CharField(blank=True, help_text='Position within the party', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='politician',
            name='photo',
            field=models.ImageField(blank=True, help_text='Politician photo (max 5MB)', null=True, upload_to='politicians/banners/', validators=[politicians.models.validate_image]),
        ),
        migrations.AlterField(
            model_name='politician',
            name='previous_party_history',
            field=models.TextField(blank=True, help_text='History of previous party affiliations'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='comment',
            field=models.TextField(blank=True, help_text='Optional comment about the rating', null=True),
        ),
        migrations.AlterField(
            model_name='rating',
            name='score',
            field=models.IntegerField(choices=[(1, '1 - Poor'), (2, '2 - Fair'), (3, '3 - Good'), (4, '4 - Very Good'), (5, '5 - Excellent')], help_text='Rating from 1 (Poor) to 5 (Excellent)'),
        ),
        migrations.AddIndex(
            model_name='initiatives',
            index=models.Index(fields=['politician', '-created_at'], name='politicians_politic_8ccfb8_idx'),
        ),
        migrations.AddIndex(
            model_name='politician',
            index=models.Index(fields=['party'], name='politicians_party_i_76772d_idx'),
        ),
        migrations.AddIndex(
            model_name='politician',
            index=models.Index(fields=['slug'], name='politicians_slug_a1e54e_idx'),
        ),
        migrations.AddIndex(
            model_name='politician',
            index=models.Index(fields=['-views'], name='politicians_views_e90b62_idx'),
        ),
        migrations.AddIndex(
            model_name='politician',
            index=models.Index(fields=['is_active', 'party'], name='politicians_is_acti_c32ed0_idx'),
        ),
        migrations.AddIndex(
            model_name='promises',
            index=models.Index(fields=['politician', 'status'], name='politicians_politic_d013da_idx'),
        ),
        migrations.AddIndex(
            model_name='promises',
            index=models.Index(fields=['-created_at'], name='politicians_created_495980_idx'),
        ),
        migrations.AddIndex(
            model_name='rating',
            index=models.Index(fields=['politician', '-created_at'], name='politicians_politic_ae7f00_idx'),
        ),
        migrations.AddIndex(
            model_name='rating',
            index=models.Index(fields=['user', '-created_at'], name='politicians_user_id_e869ca_idx'),
        ),
    ]
