# Generated by Django 5.2.8 on 2025-11-16 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("politicians", "0009_alter_initiatives_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="politician",
            name="name",
            field=models.CharField(max_length=250),
        ),
    ]
