# Generated by Django 5.2.8 on 2025-11-16 05:55

import politicians.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('politicians', '0010_alter_politician_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='politician',
            name='photo',
            field=models.ImageField(blank=True, help_text='Politician photo (max 5MB)', max_length=500, null=True, upload_to='politicians/banners/', validators=[politicians.models.validate_image]),
        ),
    ]
